server:
  port: 8090

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-db}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:postgres}
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      dialect: org.hibernate.dialect.PostgreSQLDialect

spring:
  data:
    mongobd:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27017}