server:
  port: 8090

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-db}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:postgres}
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      dialect: org.hibernate.dialect.PostgreSQLDialect

spring:
  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27017}

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      notify-ending: notify-ending
    consumer:
      group-id: order-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: INFO